# Generated by Django 6.0.3 on 2026-03-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('no_of_guests', models.IntegerField(default=0)),
                ('booking_date', models.DateField(default=None)),
            ],
        ),
    ]
