# Generated by Django 6.0.3 on 2026-03-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('no_of_guests', models.IntegerField(default=0)),
                ('booking_date', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=255)),
                ('price', models.FloatField(verbose_name=0)),
                ('inventory', models.IntegerField(verbose_name=0)),
            ],
        ),
    ]
