# Generated by Django 6.0.3 on 2026-03-31 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
